### ISSUE TITLE
Cross_spectrum code has a typo.

### ISSUE THREAD

**Issue by avik2007** [xgcm/xrft#173]
Hi there,

There is a typo in the cross_spectrum code which unfortunately makes it unusable. Line 866 in xrft.py has a line: 
  windows, _ = _apply_window(da, dim, window_type=kwargs.get("window")). "da" should be changed to da1 or
da2.

Best,
Avik

**Comment by rabernat** [comment]
Hi @avik2007 - thanks so much for this contribution! I'm concerned that this code path is not covered by our tests. Indeed that is what the [codecov report](https://app.codecov.io/gh/xgcm/xrft/blob/master/xrft/xrft.py) shows.

It looks like this code was last touched by @roxyboy in 14274233170bcba25bc08dd5ed3d93ec970f0912.

Takaya would you be willing to fix the bug and write a test for this path?

**Comment by avik2007** [comment]
Hi @rabernat,

I just pulled the code to play with it myself - Line 877 has the same problem as well.

**Comment by rabernat** [comment]
@avik2007 we would welcome a pull request from you to fix the problem!

That pull request would need to include tests to verify the correct behavior. The lack of testing for this option is what got us into this situation in the first place 🤦 .

**Comment by avik2007** [comment]
Hi Ryan,

I've never done one of these before, let me look into it. Feel free to go
ahead and fix it if I don't get to it in a reasonable time.

Best,
Avik

**Comment by rabernat** [comment]
Great! We would love to welcome you to the xrft contributor community and walk you through your first PR. This would be a good opportunity to learn since the code fix itself is trivial. The contributor guide should be useful for getting started: https://xrft.readthedocs.io/en/latest/contributor_guide.html

The overall process is:
- Fork the repo and check out a local branch
- Set up the development environment
- Create a feature branch
- Make the fix
- Write the test (it will probably go [here](https://github.com/xgcm/xrft/blob/672ddd12a85f64796d76ce5d45c7d4712d1ec821/xrft/tests/test_xrft.py#L490))
- Commit your changes and push to your remote fork
- Create PR

**Comment by roxyboy** [comment]
@avik2007 Thanks for reporting the bug. Let me know if you need help with the PR. Otherwise, I can do the fix :)

**Comment by avik2007** [comment]
Hi Takaya,

I'll give this a try and ask you for help if necessary - I personally need
to use the function sooner than later to get some plots made so I'll let
you know if I believe that I won't be able to get it done in a reasonable
amount of time.

Best,
Avik

**Comment by avik2007** [comment]
Hi all,

I submitted the pull request and added a test for it in
test_cross_spectrum. Let me know if there are any issues.

Best,
Avik

**Comment by avik2007** [comment]
@roxyboy I'm afraid I do need a bit of help. I'm running into an error using _apply_window in the test_xrft.py file. I tried changing it to xrft._apply_window() and still ran into the same issue. I'm wondering if you know how to fix this problem - xrft._apply_window is giving me the following error: 
 AttributeError: module 'xrft' has not attribute '_apply_window'. I need to use this function to apply a window correction factor in the test code.
