### ISSUE TITLE
Bug with xrft.fft with multiple dimensions

### ISSUE THREAD

**Issue by mredenti** [xgcm/xrft#189]
https://github.com/xgcm/xrft/blob/d5a89dceb1ddfc6769fec099c4d141fdeba8a050/xrft/xrft.py#L345-L349

Suppose I want to take a multidimensional real Fourier Transform along dimensions `x,y`. Then I would pass `real_dim = ['x', 'y']` which is a list and the above would raise an error as line `346` would not be true

**Comment by roxyboy** [comment]
Hi @mredenti, thanks for raising the issue. The `real_dim` is only for when you want to take a real FFT over the specified dimensions and for general FFTs, you can leave this flag blank and simply specify `dim=['x','y']`.

**Comment by lanougue** [comment]
Hello @mredenti and @roxyboy, 
xrft mainly rely on numpy.fft library. Fourier Transform of real data is directly linked to np.fft.rfftn which only handle real transform on only ONE axis at a time. The documentation of numpy.fft.rfftn says: "By default, all axes are transformed, with the real transform performed over the last axis, while the remaining transforms are complex."

The example you show is thus not feasible with xrft or numpy.fft.

**Comment by lanougue** [comment]
From a mathematical point of view, real transform should indeed be performed on only one axis !
When doing "real transform" of 1D array, the resulting quantity can be considered symmetrical respectively to the 0 frequency (this is why result has half the initial number of point +1). However, for 2D (and higher dimension) array, the real transform should be applied on only one axis because the other ones will not be symmetrical anymore.
It is thus a good thing that real transform is limited to one dimension only.
