### ISSUE TITLE
Issues with isotropic_powerspectrum: dask and freq_r axis

### ISSUE THREAD

**Issue by dhruvbalwada** [xgcm/xrft#87]
The isotropic_powerspectrum has a few problems:
a) The first wavenumber returned along the 'freq_r' dimension is a nan. Surely this should be zero or something like that. 
b) Problems when using with dask arrays. 
I get the error `TypeError: Must specify minlength argument in da.bincount`

Here is an example to reproduce it : 
```
da = xr.DataArray(np.random.rand(5,30,30),
                  dims=['time', 'y', 'x'],
                  coords={'time': np.arange(5), 'y': np.arange(30), 'x': np.arange(30)})
```

This works:  
`daisops = xrft.isotropic_powerspectrum(da, dim=['x','y'])`

But if I make da a dask array (even if it is not chunked along the dimensions along which fft is being done), then it doesn't work:
`daisops = xrft.isotropic_powerspectrum(da.chunk({'time':1}), dim=['x','y'])`

**Comment by roxyboy** [comment]
The `isotropic_powerspectrum` has not been developed for parallelization so I'm not surprised it fails for `dask.array`s

**Comment by roxyboy** [comment]
Linking issue #9 here.

**Comment by rabernat** [comment]
`isotropic_powerspectrum` should be able to work lazily. Your error suggests this might be due to the recent addition of `bincount` to dask's built in algorithms.

@dhruvbalwada - as you know we have the SWOT proposal due this week. Once that's done I'll be able to spend some time on this. Bottom line, there is nothing special about isotropic powerspectrum that should preclude the use of dask.

**Comment by roxyboy** [comment]
Oh, if dask has the API of bincount, parallelizing `isotropic_spectrum` should be quite straightforward :)

**Comment by roxyboy** [comment]
PR #128 fixed this issue.
